apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejsbook.fullname" . }}-config
  namespace: prod
data:
  KEYCLOAK_ISSUER: "{{ .Values.keycloak.issuer }}"
  PORT: "{{ .Values.env.PORT }}"